// Mocks generated by Mockito 5.4.5 from annotations
// in training_todo/testing/mocks/auth_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:training_todo/model/todo_item.dart' as _i9;
import 'package:training_todo/model/user/user.dart' as _i5;
import 'package:training_todo/repositories/auth/auth_repository.dart' as _i2;
import 'package:training_todo/repositories/todo/todo_repository.dart' as _i8;
import 'package:training_todo/services/auth/auth_service_local.dart' as _i11;
import 'package:training_todo/services/auth/auth_session_store_local.dart'
    as _i12;
import 'package:training_todo/services/database/todo_table_query.dart' as _i10;
import 'package:training_todo/util/result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<_i4.Result<_i5.User>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.User>> register({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.User>>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i8.TodoRepository {
  @override
  _i3.Future<_i4.Result<List<_i9.TodoItem>>> getItemsByCompletionStatus(
    bool? isCompleted, {
    _i10.TodoTableQuery? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getItemsByCompletionStatus,
              [isCompleted],
              {#query: query},
            ),
            returnValue: _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                this,
                Invocation.method(
                  #getItemsByCompletionStatus,
                  [isCompleted],
                  {#query: query},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                    this,
                    Invocation.method(
                      #getItemsByCompletionStatus,
                      [isCompleted],
                      {#query: query},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.TodoItem>>>);

  @override
  _i3.Future<_i4.Result<List<_i9.TodoItem>>> getItemsByDeadline({
    DateTime? first,
    DateTime? end,
    _i10.TodoTableQuery? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsByDeadline, [], {
              #first: first,
              #end: end,
              #query: query,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                this,
                Invocation.method(#getItemsByDeadline, [], {
                  #first: first,
                  #end: end,
                  #query: query,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                    this,
                    Invocation.method(#getItemsByDeadline, [], {
                      #first: first,
                      #end: end,
                      #query: query,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.TodoItem>>>);

  @override
  _i3.Future<_i4.Result<List<_i9.TodoItem>>> getItemsByCompleteTime(
    DateTime? first,
    DateTime? end, {
    _i10.TodoTableQuery? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getItemsByCompleteTime,
              [first, end],
              {#query: query},
            ),
            returnValue: _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                this,
                Invocation.method(
                  #getItemsByCompleteTime,
                  [first, end],
                  {#query: query},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                    this,
                    Invocation.method(
                      #getItemsByCompleteTime,
                      [first, end],
                      {#query: query},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.TodoItem>>>);

  @override
  _i3.Future<_i4.Result<List<_i9.TodoItem>>> getItemsByCreateTime(
    DateTime? first,
    DateTime? end, {
    _i10.TodoTableQuery? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getItemsByCreateTime,
              [first, end],
              {#query: query},
            ),
            returnValue: _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                this,
                Invocation.method(
                  #getItemsByCreateTime,
                  [first, end],
                  {#query: query},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                    this,
                    Invocation.method(
                      #getItemsByCreateTime,
                      [first, end],
                      {#query: query},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.TodoItem>>>);

  @override
  _i3.Future<_i4.Result<List<_i9.TodoItem>>> getAllItem({
    _i10.TodoTableQuery? query,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllItem, [], {#query: query}),
            returnValue: _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                this,
                Invocation.method(#getAllItem, [], {#query: query}),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<List<_i9.TodoItem>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i9.TodoItem>>>(
                    this,
                    Invocation.method(#getAllItem, [], {#query: query}),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i9.TodoItem>>>);

  @override
  _i3.Future<_i4.Result<_i9.TodoItem>> insertTodo(_i9.TodoItem? newTodo) =>
      (super.noSuchMethod(
            Invocation.method(#insertTodo, [newTodo]),
            returnValue: _i3.Future<_i4.Result<_i9.TodoItem>>.value(
              _i6.dummyValue<_i4.Result<_i9.TodoItem>>(
                this,
                Invocation.method(#insertTodo, [newTodo]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i9.TodoItem>>.value(
                  _i6.dummyValue<_i4.Result<_i9.TodoItem>>(
                    this,
                    Invocation.method(#insertTodo, [newTodo]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.TodoItem>>);

  @override
  _i3.Future<_i4.Result<void>> deleteTodo(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteTodo, [id]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteTodo, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i9.TodoItem>> changeTodo(_i9.TodoItem? newTodo) =>
      (super.noSuchMethod(
            Invocation.method(#changeTodo, [newTodo]),
            returnValue: _i3.Future<_i4.Result<_i9.TodoItem>>.value(
              _i6.dummyValue<_i4.Result<_i9.TodoItem>>(
                this,
                Invocation.method(#changeTodo, [newTodo]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Result<_i9.TodoItem>>.value(
                  _i6.dummyValue<_i4.Result<_i9.TodoItem>>(
                    this,
                    Invocation.method(#changeTodo, [newTodo]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.TodoItem>>);
}

/// A class which mocks [AuthServiceLocal].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthServiceLocal extends _i1.Mock implements _i11.AuthServiceLocal {
  @override
  _i3.Future<_i4.Result<_i5.User>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i5.User>> register({
    required String? name,
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#register, [], {
                  #name: name,
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.User>>);
}

/// A class which mocks [AuthSessionStoreLocal].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSessionStoreLocal extends _i1.Mock
    implements _i12.AuthSessionStoreLocal {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> persistSession(_i5.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#persistSession, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void signOut() => super.noSuchMethod(
    Invocation.method(#signOut, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
